### ISSUE TITLE
Append to note formatting with {content}

### ISSUE THREAD

**Issue by mikejongbloet** [KevinBatdorf/obsidian-raycast#49]
Hello!

Love this - thanks so much for creating and publishing your Raycast commands.

I saw in the tooltip the variable `{content}` which I've tried to use in my append template as I want the content to be wrapped by square brackets:
`* <small>**[{hour}:{minute}]**</small>[💭 Thought:: {content}]`

When I capture a note it's capturing like this:
![image](https://user-images.githubusercontent.com/381085/225763113-46bb1409-49cc-4d3c-b0b0-5c573603837c.png)

Essentially the variable isn't being replaced and the contents are instead being appended to the end, rather than being wrapped in the square bracket.

Mike

**Comment by marcjulianschwarz** [comment]
Thank you for reporting this issue, I will have a look at this. What command were you using?

**Comment by mikejongbloet** [comment]
It was a while back but I'm fairly sure it was "Append to Daily Note".

Cheers.

**Comment by jimmy-little** [comment]
Adding to this - I'm experiencing the same problem. 

I have the template for Append to Daily Note: 
`| {hour}:{minute} | {content} |` 
It is intended to add a row to my "log" table at the bottom of my daily note.

When I use the template this way, typing "this is a test" into Raycast-  the output in Obsidian is:
"| 09:35 | {content} |this is a test"

For a workaround, I just use `| {hour}:{minute} | ` as the template and add the final "|" character manually.

**Comment by KevinBatdorf** [comment]
Have a PR to fix this. if `{content}` is found in the template it will replace it there rather than append it to the end. 

https://github.com/KevinBatdorf/obsidian-raycast/pull/75

Will PR to the main Raycast repo in a bit and they usually merge these within a few days
