### ISSUE TITLE
[FR]more template variables

### ISSUE THREAD

**Issue by lszddz** [KevinBatdorf/obsidian-raycast#61]
Thanks for your great work!
I use the "append to daily notes" often, I want the date to be shown in my familiar form "yyyy-mm-dd"，but now it's "m/dd/yyyy", can you add more format?

**Comment by KevinBatdorf** [comment]
Sorry for the late reply. Had a busy week! For me I still see yyyy-mm-dd but it should be configurable in your settings. Go to core plugins and check the Daily Note settings:

More info: https://help.obsidian.md/Plugins/Daily+notes

![Screen Shot 2023-06-30 at 8 58 23 PM](https://github.com/KevinBatdorf/obsidian-raycast/assets/1478421/a2deb70e-928e-4955-925f-e2e9f48afd18)
