### ISSUE TITLE
What's the Obsdian? Where is link to Obsidian?

### ISSUE THREAD

**Issue by ryota-murakami** [KevinBatdorf/obsidian-raycast#67]
Hey I'm Raycast user and found out [obsidian-raycast](https://github.com/KevinBatdorf/obsidian-raycast) just by chance.  
But I don't know original Obsdian application and there is no explain, link of original version.

So I couldn't use [obsidian-raycast](https://github.com/KevinBatdorf/obsidian-raycast) if I had some interest.

**Comment by KevinBatdorf** [comment]
Hey, thanks for bringing this up. You can find it about it here https://obsidian.md/

This is just a community extension though and not affiliated with Obsidian.

**Comment by ryota-murakami** [comment]
@KevinBatdorf Thank you! I just wanted it.
