### ISSUE TITLE
Random note to be opened in the Obsidian

### ISSUE THREAD

**Issue by Tapan6598545** [KevinBatdorf/obsidian-raycast#73]
Hi Kevin,

Raycast shows me whatever is in this random node, but unfortunately, it's showing it inside in the Raycast. And I would rather see random notes open inside the Obsidian.

Thank you!
Tapan

**Comment by KevinBatdorf** [comment]
So maybe if you press enter it would open in Obsidian? Would that make sense?

**Comment by Tapan6598545** [comment]
Yes, it would be great! Unfortunately, it's not opening in Obsidian now; instead, the note opens inside Raycast. 
Please see the attached screenshot.
![Random note](https://github.com/KevinBatdorf/obsidian-raycast/assets/148795221/c077a088-d1a7-42dd-abeb-52835fca33cd)

**Comment by KevinBatdorf** [comment]
Ah gotcha! I have a fix for this now and will open a PR on Raycast later tonight. You can se the behavior in the extension settings (after the PR is live, of course)

See here for the fix and info: https://github.com/KevinBatdorf/obsidian-raycast/pull/74

**Comment by KevinBatdorf** [comment]
Raycast PR here: https://github.com/raycast/extensions/pull/9107

Will close this issue for now but if something goes wrong feel free to reopen
