### ISSUE TITLE
Append task to daily note

### ISSUE THREAD

**Issue by kaitimmer** [KevinBatdorf/obsidian-raycast#78]
I would like an option to create new tasks in a specific region of my daily note.

Currently, the "create task" command needs to have a specific file where the new task goes.

**Comment by Perchycs** [comment]
You can actually use date templates in the file path setting for the command, and use it to automatically link to your daily note. You can use the date tokens defined in the [luxon documentation](https://moment.github.io/luxon/#/formatting?id=table-of-tokens) like I have below.

<img width="313" alt="Screenshot 2024-06-07 at 1 53 53 AM" src="https://github.com/KevinBatdorf/obsidian-raycast/assets/93891752/71c24ca4-393f-4a8c-a413-b99b7d0f07d4">

**Comment by kaitimmer** [comment]
Well, that worked. Thanks a lot.
