### ISSUE TITLE
[Bug] Append task inserts text below a divider

### ISSUE THREAD

**Issue by iljapanic** [KevinBatdorf/obsidian-raycast#91]
If there is an `<hr />` divider below the heading being appended to, then the task goes below the divider. I would expect it to go below the heading instead.

A video should hopefully make the issue clear:

https://github.com/KevinBatdorf/obsidian-raycast/assets/1295321/14c1c672-efbd-4e91-8672-0b33864a2537

I've tried playing around with spacing via numerous new lines, multiple dividers, but if there is a divider below the heading, the tasks always go below the heading.

This is in no way a dealbreaker, just a pesky little bug. Thank you for making such a great plugin 🙏

**Comment by KevinBatdorf** [comment]
I looked into it but not sure there's anything that we could do unfortunately. The extension uses the `append` command from the Advanced URI Obsidian extension and the insertion is handed off to the extension.

https://vinzent03.github.io/obsidian-advanced-uri/actions/writing

**Comment by iljapanic** [comment]
Thanks for clarifying @KevinBatdorf, makes sense. I will investigate further with Advanced URI Obsidian and update this thread if I find a solution.

I will close the issue as it's not related to Obsidian Raycast extension.
