### ISSUE TITLE
Looks like templater isn't triggered when creating new daily note from raycast

### ISSUE THREAD

**Issue by constpetrov** [KevinBatdorf/obsidian-raycast#92]
Part of the template I have for the daily note in obsidian is `<% tp.file.cursor() %>` to set the cursor to the specific position when file is created.
When I create a new daily note from Obsidian it works as intended. However, when the creation of a new daily note is triggered from Raycast this part of the template isn't processed. It stays in the file as if it is some text, and the cursor doesn't move to the intended position.

**Comment by KevinBatdorf** [comment]
It might be a limitation of the [Advanced URI plugin](https://publish.obsidian.md/advanced-uri-doc/Actions/Writing)? 

The Raycast extension would prepare a link like this (update with your vault name):
obsidian://advanced-uri?vault=<your-vault>&daily=true&data=Hello%2520World&mode=append

Does the same thing happen?

**Comment by constpetrov** [comment]
Yes, unfortunatelly it seems to be the case.
